services:
  - type: web
    name: labwlbook
    env: python
    region: singapore
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn --timeout 600 --workers 1 --threads 2 --worker-class sync app:app"
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
      - key: WEB_CONCURRENCY
        value: 1
